name: Maven Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and Test
      id: build-test
      run: |
        echo "Building project..."
        mvn -B clean install
        echo "✅ All checks passed!"

    - name: Comment on PR - Success
      if: github.event_name == 'pull_request' && success()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '## ✅ Build Successful!\n\nYour changes have passed all checks:\n- ✅ Maven build completed\n- ✅ All tests passed\n\nReady for review! 🚀'
          })

    - name: Comment on PR - Failed
      if: github.event_name == 'pull_request' && failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '## ❌ Build Failed\n\nPlease fix the issues and try again.\n\n**What to do:**\n1. Check the build logs above for error details\n2. Fix the issues in your code\n3. Push your changes to trigger a new build\n\n**Need help?** Check the [Actions tab](https://github.com/${{ github.repository }}/actions) for detailed logs.'
          })
